### ISSUE TITLE
Aesthetic issues

### ISSUE THREAD

**Issue by Zpiboo** [theskyblockman/life-chest#24]
Sadly, the absence of margins gives the impression of a lack of aesthetic care.
May I add that files and folders in the grid view would look much better with rounded corners. Finally, the folder icon looks terrible in black. Please fix that.

en gros quand 'y a pas de marges c'est moche (oui bon j'exagère)
et ajoute des coins arrondis stp

**Comment by theskyblockman** [comment]
Fixed issue excepted for the absence of margins which should be a little be more specific in 2769941

**Comment by theskyblockman** [comment]
Fixed in 895024f
